openapi: 3.0.1
info:
  title: Samnordisk runtextdatabas söktjänst API
  description: Samnordisk runtextdatabas (SRD) söktjänst API. Specification för Riksantikvarieämbetets
    forskningsplattform för runor inom projektet Evighetsrunor. API:et används för
    att hitta och söka i runtexter i SRD. Sökresultaten innehåller endast grundinformationen
    om runtexterna (id:n, text och geografiska koordinater). Ytterligare metadata
    runt runtexterna, bärarobjekt samt kopplad information hämtas via K-SAMSÖK
  contact:
    url: https://www.raa.se/kulturarv/runor-och-runstenar/projektet-evighetsrunor/
  version: 0.9.3
servers:
  - description: Uppsala Universitet Evighetsrunor API - TEST
    url: http://runor.test.uu.se/rest/
#  - description: SwaggerHub API Auto Mocking
#    url: 'https://virtserver.swaggerhub.com/uu/evighetsrunor/api/1.0.0-TODO'
paths:
  /signums:
    get:
      tags:
        - Enkel sökning
      summary: Hämtar lista med signum
      description: Hämta en lista med signum som kan användas vid enkel sökning (typeahead)
        på signum
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
        - name: matching_text
          in: query
          description: Del av signum att matcha mot
          schema:
            type: string
        - name: page
          in: query
          description: Index för önskad resultatsida
          schema:
            type: number
            format: number
        - name: size
          in: query
          description: Storlek på sidor
          schema:
            type: number
            format: number
        - name: sort
          in: query
          description: Attribut som man vill använda föra att sortera svaret, tex "sort=id",
            eller "sort=id,desc" om man vill ha svaret i fallande ordning.
          schema:
            type: string
            format: sort
      responses:
        200:
          description: En lista med signum
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedSignumResponse'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /places:
    get:
      tags:
        - Enkel sökning
      summary: Hämtar lista med platser
      description: Hämta en lista med platser som kan användas vid enkel sökning (typeahead)
        på plats
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
        - name: matching_text
          in: query
          description: Del av namn på plats att matcha mot
          schema:
            type: string
      responses:
        200:
          description: En lista med platser
          content:
            application/json:
              schema:
                type: array
                example:
                  - id: ca79d466-888f-4011-b5bd-35fc6dd1d622
                    name: Abrahamstorp
                  - id: 25a4de16-c421-41ed-8d17-fc465fd03db1
                    name: Ackarby
                  - id: b70ec612-cef6-446d-afc0-4e3387804842
                    name: '...'
                items:
                  $ref: '#/components/schemas/SelectionItem'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /selection/groups:
    get:
      tags:
        - Avancerad sökning
      summary: Hämtar lista med urvalsgrupper
      description: Hämtar lista med urvalsgrupper att användas när man sätter filtervillkor
        för en avancerad sökning
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
      responses:
        200:
          description: En lista med urvalsgrupper
          content:
            application/json:
              schema:
                type: array
                example:
                  - id: 161ab23e-7566-43a0-9dbe-c7f237f27765
                    name: Plats
                  - id: d3c41141-ef42-4ef3-9cbb-3d49fa6acffe
                    name: Socken
                  - id: 30ba8d99-f27b-48fc-8048-7892eb3a0fbc
                    name: Härrad
                  - id: b95dc24b-a1f6-4310-8a9e-3d0264f0f53e
                    name: '...'
                items:
                  $ref: '#/components/schemas/SelectionGroup'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /selection/groups/{group_id}:
    get:
      tags:
        - Avancerad sökning
      summary: Hämtar lista med urval
      description: Hämtar lista med urval för en urvalsgrupp att användas när man
        sätter filtervillkor för en avancerad sökning
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: Id för urvalsgrupp
          required: true
          schema:
            type: string
        - name: matching_text
          in: query
          description: Del av namn på urval att matcha mot
          schema:
            type: string
      responses:
        200:
          description: En lista med urval
          content:
            application/json:
              schema:
                type: array
                example:
                  - id: ca79d466-888f-4011-b5bd-35fc6dd1d622
                    name: Abrahamstorp
                  - id: 25a4de16-c421-41ed-8d17-fc465fd03db1
                    name: Ackarby
                  - id: b70ec612-cef6-446d-afc0-4e3387804842
                    name: '...'
                items:
                  $ref: '#/components/schemas/SelectionItem'
        404:
          description: (Not found). Gruppen saknas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: 404
                message: Gruppen saknas
                path: /selection/12/test
                timestamp: 1990-12-31T23:59:60Z
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /translationtypes:
    get:
      tags:
        - Avancerad sökning
      summary: Hämtar alla översättningstyper
      description: Översättningstyper att använda när en sökfråga sätts samman
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
      responses:
        200:
          description: (OK)
          content:
            application/json:
              schema:
                type: array
                example:
                  - id: da0b20c8-e036-456b-8f0a-6aeb06105f9a
                    name: Fornvästnordiska
                    proper_name_searchable: true
                    is_complete: true
                    method: NORMALISERING
                  - id: ca79d466-888f-4011-b5bd-35fc6dd1d623
                    name: Engelska
                    proper_name_searchable: false
                    is_complete: false
                    method: OVERSATTNING
                items:
                  $ref: '#/components/schemas/RunicTextTranslationType'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /search:
    get:
      tags:
        - Enkel sökning
      summary: Enkel sökning. Sök efter runtexter med del av plats eller signum
      description: Söker efter runtexter med del av plats eller signum
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
        - name: matching_text
          in: query
          description: Söksträng
          required: true
          schema:
            type: string
        - name: search_field
          in: query
          description: Sökfält
          required: true
          schema:
            type: string
            enum:
              - PLACE
              - SIGNUM
      responses:
        200:
          description: (OK)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RunicInscription'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Avancerad sökning
      summary: Avancerad sökning i runtexter enligt sökvillkor
      description: Sök i runtexter enligt kombinerade sökvillkor för text samt filtrering
        enligt urval
      parameters:
        - name: edition_id
          in: path
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/SearchQuery'
        required: true
      responses:
        200:
          description: Hittade runtexter med markering av hittade ord
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchResult'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: query
  /map:
    get:
      tags:
        - Karta
      summary: Hämtar alla geografiska punkter
      description: Hämtar alla geografiska punkter där runinskriptioner finns eller
        har hittats
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
        - name: bbox
          in: query
          description: |
            Anger koordinater i kommaseparerad lista för spatial utsökning i bboxformat; left,top,bottom,right. Exempel 688232.203,6332689.351,713304.203,6345041.351 Koordinatsystem antas vara ?.  TODO Vilket koordinatsystem skall vi använda? SR-ORG:7483 EPSG:3857 -- WGS84 Web Mercator (Auxiliary Sphere) för att visa på Google-maps?
          required: true
          schema:
            type: string
      responses:
        200:
          description: (OK). Poster hittades
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RunicInscriptionGeoPosition'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /inscriptions:
    get:
      tags:
        - Runtexter
      summary: Hämtar en lista med runinskrifter
      description: Hämtar en lista med runinskrifter för en viss utgåva
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Index för önskad resultatsida
          schema:
            type: number
            format: number
        - name: size
          in: query
          description: Storlek på sidor
          schema:
            type: number
            format: number
        - name: sort
          in: query
          description: Attribut som man vill använda föra att sortera svaret, tex "sort=id",
            eller "sort=id,desc" om man vill ha svaret i fallande ordning.
          schema:
            type: string
            format: sort
      responses:
        200:
          description: (OK). Posten hittades.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedRunicInscriptionResponse'
        400:
          description: (Bad request). Felaktigt indata angavs till tjänsten (typiskt valideringsfel).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: (Not found). Angiven post kunde inte hittas.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: 404
                message: Signum eller URI saknas
                path: /selection/12/test
                timestamp: 1990-12-31T23:59:60Z
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /inscriptions/{id}:
    get:
      tags:
        - Runtexter
      summary: Hämtar en runinskrift med hjälp av signum eller URI
      description: Hämtar en runinskrift med hjälp av signum eller URI
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: Signum eller URI
          required: true
          schema:
            type: string
      responses:
        200:
          description: (OK). Post hittades
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunicInscription'
        404:
          description: (Not found). Ingen träff
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: 404
                message: Signum eller URI saknas
                path: /selection/12/test
                timestamp: 1990-12-31T23:59:60Z
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /editions:
    get:
      tags:
        - Utgåva
      summary: Hämtar en lista med utgåvor
      description: Hämtar en lista med utgåvor
      responses:
        200:
          description: (OK). Poster hittades
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Edition'
        404:
          description: (Not found). Ingen träff
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: 404
                message: Utgåvor saknas
                path: /editions
                timestamp: 2001-12-31T23:59:60Z
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /editions/{edition_id}/download:
    get:
      tags:
        - Utgåva
      summary: Hämtar all data i en utgåva
      description: 'Hämtar en fil som innehåller all data i en utgåva av SRD. TODO:
        bestämma format'
      parameters:
        - name: edition_id
          in: path
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
      responses:
        200:
          description: (OK). Poster hittades
          content: {}
        404:
          description: (Not found). Ingen träff
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/Error'
            application/json:
              example:
                status: 404
                message: Utgåva saknas
                path: /editions/1987
                timestamp: 2018-12-31T23:59:60Z
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/Error'

  /echo/{message}:
      get:
        summary: Tjänst avsedd för att utföra sambandstest. Tjänsten returnerar det argument soma angavs som inparameter i anropet.
        parameters:
          - in: path
            name: message
            description: Värdet för det 'eko' som ska returneras tillbaka till klienten.
            required: true
            schema:
              type: string
              example: "Hurra! Anropet lyckades."
        responses:
          '200':
            description: (OK). Ett json-objekt med attributet 'echo' returneras.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Echo'
          '500':
            description: (Internal server error). Ett oväntat fel inträffade.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
        tags:
          - Övriga tjänster
components:
  schemas:
    Echo:
      type: object
      description: Objekt för att representera svaret till echo-tjänsten.
      properties:
        echo:
          description: Anger värdet som som skickades in till tjänsten.
          type: string
          example: Hurra! Tjänsten svarar. Anropet lyckades.
    Edition:
      required:
        - id
      type: object
      properties:
        id:
          type: string
          description: Identitet på utgåvan
          example: "2018"
        name:
          type: string
          description: Namn på utgåvan
          example: 2018 års utgåva av Samnordisk runtextdatabas
        latest:
          type: boolean
          description: Anger om utgåvan är den aktuella (senast utgivna)
          example: true
        download:
          type: string
          description: Anger URL för att ladda ner all data i en utgåva
          example: /editions/2018/download
      description: En utgåva (version) av SRD
    SearchQuery:
      required:
        - query
      type: object
      properties:
        query:
          type: array
          description: Textsökfråga
          items:
            $ref: '#/components/schemas/TextQueryGroup'
        filter:
          type: array
          description: Filtrering
          items:
            $ref: '#/components/schemas/Selection'
      description: Sökfråga som används för att sätta sökvillkor vid avancerad sökning
        i SRD
    TextQueryGroup:
      required:
        - condition
      type: object
      properties:
        op:
          type: string
          description: Anger logisk operator för användas när flera sökfrågor kombineras.
            Första frågan i en TextQueryGroup behöver inte ha en logisk operator
          enum:
            - AND
            - OR
            - NOT
        condition:
          type: array
          items:
            $ref: '#/components/schemas/TextQuery'
      description: Gruppering (tänk parenteser) av sökvillkor i en avancerad sökfråga
    TextQuery:
      required:
        - matching_text
        - proper_name_search
      type: object
      properties:
        op:
          type: string
          description: Anger logisk operator för användas när flera sökfrågor kombineras.
            Första frågan i en TextQuery behöver inte ha en logisk operator
          enum:
            - AND
            - OR
            - NOT
        matching_text:
          type: string
          description: Söktext
          example: þaiR
        proper_name_search:
          type: string
          description: Anger hur/om sökning skall ske i egennamn
          enum:
            - INCLUDE
            - EXCLUDE
            - ONLY
        translation_type_id:
          type: string
          description: Anger i vilken översättning sökningen skall ske
          example: da0b20c8-e036-456b-8f0a-6aeb06105f9a
      description: Sökfråga som används för att sätta villkor för textsökning i SRD
    SearchResult:
      required:
        - inscription
      type: object
      properties:
        inscription:
          type: array
          description: Runinskrifter
          items:
            $ref: '#/components/schemas/RunicInscription'
        found_words_index:
          type: array
          example:
            - 0
            - 4
            - 6
          items:
            type: integer
      description: Resultat av en sökfråga
    PagedSignumResponse:
      type: object
      properties:
        signum:
          type: array
          description: Lista med signum
          example:
            - Öl 4 $
            - Öl Fv1911;274 B $
            - '...'
          items:
            type: string
        totalpages:
          type: integer
          description: Totalt antal sidor som kan hämtas
          example: 84
        totalElements:
          type: integer
          description: Totalt antal objekt som kan hämtas
          example: 8345
        last:
          type: boolean
          description: Anger om aktuell sida är den sista
          example: false
        sort:
          type: string
          description: Anger vilken sortering som använts
          example: sort=id
        first:
          type: boolean
          description: Anger om aktuell sida är den första
          example: true
        numberOfElements:
          type: integer
          description: Antal objekt i aktuellt svar
          example: 100
        size:
          type: integer
          description: Anger antal objekt per sida
          example: 100
        number:
          type: integer
          description: Sidnummer
          example: 0
      description: Paginerat svar med signum
    PagedRunicInscriptionResponse:
      type: object
      properties:
        content:
          type: array
          description: Runinskrifter
          items:
            $ref: '#/components/schemas/RunicInscription'
        totalpages:
          type: integer
          description: Totalt antal sidor som kan hämtas
          example: 84
        totalElements:
          type: integer
          description: Totalt antal objekt som kan hämtas
          example: 8345
        last:
          type: boolean
          description: Anger om aktuell sida är den sista
          example: false
        sort:
          type: string
          description: Anger vilken sortering som använts
          example: sort=id
        first:
          type: boolean
          description: Anger om aktuell sida är den första
          example: true
        numberOfElements:
          type: integer
          description: Antal objekt i aktuellt svar
          example: 100
        size:
          type: integer
          description: Anger antal objekt per sida
          example: 100
        number:
          type: integer
          description: Sidnummer
          example: 0
      description: Paginerat svar med runinskription
    RunicInscription:
      required:
        - signum
        - translation
        - uri
      type: object
      properties:
        signum:
          type: string
          description: Signum
          example: Öl 4 $
        alt_signum:
          type: array
          description: Alternativt signum
          example:
            - B 1063
            - L 1318
            - '...'
          items:
            type: string
        uri:
          type: string
          description: Persistent identifierare för runinskriften (används för att
            hämta information från K-SAMSÖK)
          example: https://kulturarvsdata.se/objekt/runtext/d778ec61-8f70-4105-ba93-e928328173e2
        object_uri:
          type: string
          description: Persistent identifierare för bärare av runinskriften (används
            för att hämta information från K-SAMSÖK)
          example: https://kulturarvsdata.se/objekt/lamning/7b70c89a-c191-4d73-4455fd5dd2a7
        last_update_time:
          type: string
          description: Anger tidpunkten när senaste uppdatering av informationen om
            denna runinskrift gjorts
          format: dateTime
          example: 2018-01-07T13:00:60Z
        translation:
          type: array
          description: Översättning av runtext
          items:
            $ref: '#/components/schemas/RunicTextTranslation'
        position:
          $ref: '#/components/schemas/RunicInscriptionGeoPosition'
      description: Grundinformation för en runinskription
    RunicTextTranslation:
      required:
        - text
      type: object
      properties:
        text:
          type: string
          description: Runtext
          example: '...-abi · þaiR --tu · raisa · stein- · eftiR · rantui · moþor
            sina'
        translation_type:
          $ref: '#/components/schemas/RunicTextTranslationType'
      description: En transliterering/normalisering/översättning av en runtext
    RunicTextTranslationType:
      required:
        - id
        - is_complete
        - method
        - name
        - proper_name_searchable
      type: object
      properties:
        id:
          type: string
          description: Id för översättningstypen
          example: da0b20c8-e036-456b-8f0a-6aeb06105f9a
        name:
          type: string
          description: Namn på översättningstypen
          example: Fornvästnordiska
        proper_name_searchable:
          type: boolean
          description: Anger om texter av denna översättningstyp har sökbara egennamn
          example: true
        is_complete:
          type: boolean
          description: Anger om texter av denna översättningstyp är kompletta
          example: true
        method:
          type: string
          description: Anger översättningsmetod
          example: NORMALISERING
          enum:
            - NORMALISERING
            - TRANSLITERERING
            - OVERSATTNING
      description: Översättningstyp, transliterering/normalisering/översättning av
        en runtext
    RunicInscriptionGeoPosition:
      required:
        - current
        - signum
        - uri
      type: object
      properties:
        signum:
          type: string
          description: Signum
          example: Öl 4 $
        uri:
          type: object
          description: Persistent identifierare för runinskriften
          example: https://kulturarvsdata.se/objekt/runtext/d778ec61-8f70-4105-ba93-e928328173e2
        current:
          $ref: '#/components/schemas/Geometry'
        orginal:
          $ref: '#/components/schemas/Geometry'
      description: Geografiska positioner med nuvarande och ev. ursprungligt läge
        att rendera på en bakgrundskarta
    SelectionGroup:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
          description: Identitet för urvalsgruppen
          example: b86b72cb-bc22-45fc-90cb-eaf213d3aaf9
        name:
          type: string
          description: Namn på urvalsgruppen
          example: Socken
      description: Urvalsgrupp (tex Föremål, Korsform, Material etc)
    SelectionItem:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
          description: Identitet för urvalet
          example: c387aad1-9b4b-4c8c-ad0d-0bb4eaf605d6
        name:
          type: string
          description: Namn på urval
          example: Bro
      description: Ett urval (tex socken Bro)
    Selection:
      required:
        - item
        - op
      type: object
      properties:
        op:
          type: string
          description: Logisk operator att användas när filter kombineras
          enum:
            - AND
            - NOT
        item:
          $ref: '#/components/schemas/SelectionItem'
      description: Kompletterande filter med urvalsgrupper

    Geometry:
      type: object
      description: |
        Objektrepresentation av en geografisk position uttryckt enligt GeoJSON[2016] specificatioenen. Se https://tools.ietf.org/html/rfc7946.
        Notera att koordinatsystemet för angivna koordinater är uttryckta i WGS84. Se: https://tools.ietf.org/html/rfc7946#section-4
        "The coordinate reference system for all GeoJSON coordinates is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) [WGS84] datum,
        with longitude and latitude units of decimal degrees.
        This is equivalent to the coordinate reference system identified by the Open Geospatial Consortium (OGC) URN urn:ogc:def:crs:OGC::CRS84."
      required:
        - coordinates
        - type
      properties:
        type:
          description: |
            Anger tillåtna koordinattyper för geometrin.
          type: string
          enum:
            - Point
          example: Point
        coordinates:
          description: |
            Anger koordinater för geometrin. Exemplet uttryckt enligt longitude, latitude.
            Se: https://tools.ietf.org/html/rfc7946#appendix-A.1
            "Point coordinates are in x, y order (easting, northing for projected coordinates, longitude, and latitude for geographic coordinates)".
          type: array
          items:
            type: number
            example: "18.31511, 57.159624"

    Geometry-geojson2008:
      required:
        - coordinates
        - type
      type: object
      properties:
        type:
          type: string
          example: Point
          enum:
            - Point
            - Linestring
            - Polygon
        crs:
          required:
            - type
          type: object
          properties:
            type:
              type: string
              enum:
                - name
            properties:
              required:
                - name
              type: object
              properties:
                name:
                  type: string
                  description: Anger koordinatsystemet för geometrierna
                  example: EPSG:3857
        coordinates:
          type: array
          items:
            type: array
            items:
              type: array
              example:
                - 57.6353939
                - 18.2954135
              items:
                type: number
      description: |-
        Geometrier uttryckta i geoJSON formatet och benämns som GeoJSON[2008]. Se specifikationen http://geojson.org/.

        TODO Vilket koordinatsystem skall vi använda? SR-ORG:7483 EPSG:3857 -- WGS84 Web Mercator (Auxiliary Sphere) för att visa på Google-maps?
    Error:
      required:
        - message
        - path
        - status
        - timestamp
      type: object
      properties:
        status:
          type: integer
          description: Http statuskod
          example: 500
        message:
          type: string
          description: Innehåller ett felmeddelande tänkt att presenteras för slutanvändare
          example: Tekniskt fel, försök senare
        exception:
          type: string
          description: Innehåller ett felmeddelande tänkt för tekniker vid felsökning
          example: java.lang.NullPointerException
        path:
          type: string
          description: Anger den resourcepath där felet uppstod
          example: /selection/13/Test
        timestamp:
          type: string
          description: Anger tidpunkten när felet inträffade. Tidpunkt angiven som
            date-time, se RFC3339 (Internet Date/Time Format)
          format: dateTime
          example: 2019-01-04T23:59:60Z
      description: Ett fel
  parameters:
    editionParameter:
      name: edition_id
      in: query
      description: Id för önskad utgåva
      required: true
      schema:
        type: string
      example: 2020
    pageParameter:
      name: page
      in: query
      description: Index för önskad resultatsida
      schema:
        type: number
        format: number
      example: 0
    sizeParameter:
      name: size
      in: query
      description: Storlek på sidor
      schema:
        type: number
        format: number
      example: 10
    sortParameter:
      name: sort
      in: query
      description: Attribut som man vill använda föra att sortera svaret, tex "sort=id",
        eller "sort=id,desc" om man vill ha svaret i fallande ordning.
      schema:
        type: string
        format: sort
